name: Update Google Play cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1" # toda segunda 06:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci
        working-directory: .

      - name: Generate cards
        run: node scripts/gplay-cards.js
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Commit & push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: update Google Play cards"
            git push
          else
            echo "No changes."
          fi
